### ISSUE TITLE
markR1R2 might be improved with string ==

### ISSUE THREAD

**Issue by jeffallen** [surgebase/porter2#1]
You are currently doing char by char equality checking. If you checked a subslice for equality to e.g. "gener" the runtime will use highly the optimized memcmp Instead of lots if one byte reads. But you run the risk of making a lit of garbage, have to check that too, I guess. ☺

**Comment by zhenjl** [comment]
@jeffallen do you mean converting the subslice into a string and doing a = on the strings? That would create quite a bit of garbage, I think. That's the main reason I went with rune by rune check. Though to be honest I did not test the string comparison scenario so not sure if it's really that big of an issue.

**Comment by jeffallen** [comment]
If the compiler can prove that the string subslice does not escape (it will
be able to, I'm 90% sure) then the slice will be constructed on the stack.
use "go test -gcflags=-m" to see escape analysis.

memcmp beats byte compare, use it if you possibly can.

**Comment by zhenjl** [comment]
I tried this

```
	if len(rs) >= 6 && string(rs[:6]) == "commun" {
		r1 = 6
	}

	if r1 == -1 && len(rs) >= 5 {
		s := string(rs[:5])
		if s == "gener" || s == "arsen" {
			r1 = 5
		}
	}
```

The result is 443ms running compare.go with string conversion and comparison, and 300ms with just byte-by-byte comparison.

**Comment by jeffallen** [comment]
Interesting. I guessed it was right on the limit of when memcmp helps. To get real benefits from memcmp versus byte by byte, you need to get up into the 20-64 byte zone, I think. That way memcmp is walking through a significant part of one cache line.

Thanks for trying the experiment. Hope you learned something interesting, I did. :)

**Comment by zhenjl** [comment]
Certainly interesting to verify. Thanks for opening the issue.
